#Travis CI config file

notifications:
    email:
        on_success: change
        on_failure: change

branches:
    only:
        - master

before_script:
  - /usr/bin/rails db:migrate RAILS_ENV=test
