# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 548565c448b3ebd9da3a35be846cd9ea7cb23b0eb9020abc746a7033f6ad4d5c5bef601b015d40c196f3c06b430631c0f67cbdfe09c765b1ef2dab092fda36ad

test:
  secret_key_base: a16d34cb5b69306d027cc9aa191505627ee0b8f633deb4bd1be3fc3bd00138ec8eaddf3393001f9878ac5878cf84b8b054329440d739cd21c91139528958e727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
